import asyncio
import json
import logging
import time
from uuid import uuid4

from fastapi.responses import JSONResponse
from starlette.datastructures import Headers
from starlette.requests import Request

from open_webui.models.schedules import Schedules
from open_webui.models.users import Users
from open_webui.utils.chat import generate_chat_completion
from open_webui.env import SRC_LOG_LEVELS

log = logging.getLogger(__name__)
log.setLevel(SRC_LOG_LEVELS["MAIN"])

SCHEDULE_CHECK_INTERVAL = 60  # Check every 60 seconds


def _create_mock_request(app):
    """Create a mock Request object for internal use."""
    return Request(
        {
            "type": "http",
            "asgi.version": "3.0",
            "asgi.spec_version": "2.0",
            "method": "POST",
            "path": "/internal/schedule",
            "query_string": b"",
            "headers": Headers({}).raw,
            "client": ("127.0.0.1", 12345),
            "server": ("127.0.0.1", 80),
            "scheme": "http",
            "app": app,
        }
    )


async def _execute_schedule(app, schedule):
    """Execute a single schedule by calling generate_chat_completion."""
    run_id = str(uuid4())
    run = Schedules.insert_new_run(run_id, schedule.id)

    if not run:
        log.error(f"Failed to create run record for schedule '{schedule.name}'")
        return

    Schedules.update_run_by_id(
        run_id,
        {"status": "running", "started_at": int(time.time())},
    )

    try:
        user = Users.get_user_by_id(schedule.user_id)
        if not user:
            raise ValueError(f"Schedule owner user '{schedule.user_id}' not found")

        models = app.state.MODELS
        model_id = schedule.model_id

        if model_id not in models:
            raise ValueError(f"Model '{model_id}' not found")

        request = _create_mock_request(app)

        payload = {
            "model": model_id,
            "messages": [{"role": "user", "content": schedule.prompt}],
            "stream": False,
            "tool_ids": schedule.tools if schedule.tools else [],
            "filter_ids": schedule.filters if schedule.filters else [],
            "metadata": {
                "task": "schedule_run",
                "schedule_id": schedule.id,
            },
        }

        response = await generate_chat_completion(
            request, form_data=payload, user=user
        )

        # Extract AI response content
        if isinstance(response, dict):
            choices = response.get("choices", [])
            if choices and choices[0].get("message", {}).get("content"):
                ai_content = choices[0]["message"]["content"]
            else:
                ai_content = "No response generated by the model."
        elif isinstance(response, JSONResponse):
            body = response.body.decode("utf-8")
            data = json.loads(body)
            choices = data.get("choices", [])
            if choices and choices[0].get("message", {}).get("content"):
                ai_content = choices[0]["message"]["content"]
            else:
                ai_content = "No response generated by the model."
        else:
            ai_content = str(response)

        result_text = (
            f"## Schedule: {schedule.name}\n\n"
            f"**Model:** {schedule.model_id}\n"
            f"**Prompt:** {schedule.prompt}\n"
            f"**Tools:** {', '.join(schedule.tools) if schedule.tools else 'None'}\n\n"
            f"---\n\n"
            f"## AI Response\n\n"
            f"{ai_content}\n\n"
            f"---\n\n"
            f"*Completed at {time.strftime('%Y-%m-%d %H:%M:%S')}*"
        )

        Schedules.update_run_by_id(
            run_id,
            {
                "status": "completed",
                "result": result_text,
                "completed_at": int(time.time()),
            },
        )

        log.info(f"Schedule '{schedule.name}' executed successfully (run {run_id})")

    except Exception as e:
        log.exception(f"Error executing schedule '{schedule.name}': {e}")
        error_text = (
            f"## Schedule: {schedule.name}\n\n"
            f"**Model:** {schedule.model_id}\n"
            f"**Prompt:** {schedule.prompt}\n\n"
            f"---\n\n"
            f"## Error\n\n"
            f"Failed to execute: {str(e)}\n\n"
            f"---\n\n"
            f"*Failed at {time.strftime('%Y-%m-%d %H:%M:%S')}*"
        )
        Schedules.update_run_by_id(
            run_id,
            {
                "status": "failed",
                "result": error_text,
                "completed_at": int(time.time()),
            },
        )

    # Advance schedule to next run time (or deactivate if 'once')
    Schedules.advance_schedule(schedule.id)


async def periodic_schedule_check(app):
    """Background task that periodically checks for and executes due schedules."""
    log.info("Schedule executor started")

    # Wait a bit for the app to fully initialize (models loaded, etc.)
    await asyncio.sleep(30)

    while True:
        try:
            now = int(time.time())
            due_schedules = Schedules.get_due_schedules(now)

            if due_schedules:
                log.info(f"Found {len(due_schedules)} due schedule(s) to execute")

            for schedule in due_schedules:
                try:
                    await _execute_schedule(app, schedule)
                except Exception as e:
                    log.exception(
                        f"Unhandled error executing schedule '{schedule.name}': {e}"
                    )

        except Exception as e:
            log.exception(f"Error in schedule check loop: {e}")

        await asyncio.sleep(SCHEDULE_CHECK_INTERVAL)
