import ast
import json
import logging

from fastapi.responses import JSONResponse

from open_webui.utils.chat import generate_chat_completion
from open_webui.utils.tools import get_updated_tool_function

log = logging.getLogger(__name__)

MAX_TOOL_CALL_RETRIES = 5


async def execute_with_tools(request, payload, metadata, user):
    """
    Non-streaming tool execution loop for schedule runs.
    Calls the model, and if it responds with tool_calls, executes them
    and re-calls the model until it returns content.
    """
    for attempt in range(MAX_TOOL_CALL_RETRIES):
        response = await generate_chat_completion(
            request, form_data=payload, user=user
        )

        # Normalize response to a dict
        if isinstance(response, dict):
            data = response
        elif isinstance(response, JSONResponse):
            data = json.loads(response.body.decode("utf-8"))
        else:
            return str(response)

        choices = data.get("choices", [])
        if not choices:
            return "No response generated by the model."

        message = choices[0].get("message", {})
        tool_calls = message.get("tool_calls", [])
        content = message.get("content")

        # If no tool_calls, we have the final answer
        if not tool_calls:
            return content or "No response generated by the model."

        log.debug(
            f"Tool call attempt {attempt + 1}: model requested "
            f"{len(tool_calls)} tool call(s)"
        )

        # Execute each tool call
        tools = metadata.get("tools", {})
        tool_messages = [
            {"role": "assistant", "content": content, "tool_calls": tool_calls}
        ]

        for tc in tool_calls:
            tc_id = tc.get("id", "")
            func_name = tc.get("function", {}).get("name", "")
            func_args_str = tc.get("function", {}).get("arguments", "{}")

            try:
                func_params = json.loads(func_args_str)
            except (json.JSONDecodeError, ValueError):
                try:
                    func_params = ast.literal_eval(func_args_str)
                except (ValueError, SyntaxError):
                    log.warning(
                        f"Could not parse tool arguments for '{func_name}': "
                        f"{func_args_str}"
                    )
                    func_params = {}

            result = f"Tool '{func_name}' not found"
            if func_name in tools:
                tool = tools[func_name]
                spec = tool.get("spec", {})
                allowed = spec.get("parameters", {}).get("properties", {}).keys()
                func_params = {k: v for k, v in func_params.items() if k in allowed}

                try:
                    tool_fn = get_updated_tool_function(
                        function=tool["callable"],
                        extra_params={
                            "__messages__": payload.get("messages", []),
                            "__files__": metadata.get("files", []),
                            "__content_blocks__": [],
                        },
                    )
                    tool_result = await tool_fn(**func_params)
                    result = str(tool_result) if tool_result else ""
                except Exception as e:
                    log.warning(
                        f"Tool '{func_name}' execution failed with "
                        f"params {func_params}: {e}"
                    )
                    result = str(e)
            else:
                log.warning(
                    f"Tool '{func_name}' not found in resolved tools: "
                    f"{list(tools.keys())}"
                )

            tool_messages.append(
                {"role": "tool", "tool_call_id": tc_id, "content": result}
            )

        # Update payload with tool results and re-call
        payload = {
            **payload,
            "stream": False,
            "messages": [*payload["messages"], *tool_messages],
        }

    return "Max tool call retries reached without a final response."
